# Generated by Django 4.2.5 on 2025-11-20 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vapp', '0002_userinfo_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
