# Generated by Django 6.0.2 on 2026-02-26 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vapp', '0004_contactmessage_product_brand_product_stock_review_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='city',
            field=models.CharField(default='N/A', max_length=50),
        ),
    ]
